### PR TITLE
Add Chinese translation of README.md

### PR DESCRIPTION
**Pull request by hehongyu1995**
Thank you very much for this interesting tutorial you provided.  I have translated README.md into Chinese. I hope that more Chinese people can read it. I will submit other chapters translated version in few days.

### CODE REVIEW

**Comment by nicklockwood** [comment]
Thanks for doing this! It's probably going to introduce a bit of a maintenance problem to merge this into the main repo though, since it will need to be updated for each new chapter.

I think it might make more sense to make it a branch off master with the translations made in-place. Or alternatively I could just link people to your fork and then you could keep that up to date without needing to make PRs each time. What do you think?

**Comment by hehongyu1995** [comment]
OK, I understand your concerns. so please create a new branch, and I will submit my translation work to it ~

**Comment by nicklockwood** [comment]
@hehongyu1995 I'm going to restructure the project a bit to make it easier to maintain separate translations moving forward without having to constantly modify history / retag releases, etc.

In the meantime, please feel free to push any further changes to this branch. Also, I have the diagrams available in Keynote format if that would be useful to you? Otherwise, I'm happy to update those myself if you could provide translation notes.

Thanks again!

**Comment by hehongyu1995** [comment]
@nicklockwood Yes, Keynote file would be useful, you can send them via email to hehongyu1995@gmail.com. So, should I continue make PR or submit translation to a new branch now?

**Comment by nicklockwood** [comment]
@hehongyu1995 continue with this PR for now, I'll create a branch later.

**Comment by nicklockwood** [comment]
@hehongyu1995 I've created a new branch here with your current changes: https://github.com/nicklockwood/RetroRampage/tree/translations/zh-Hans - please make any further PRs agains this branch. Thanks!

**Comment by nicklockwood** [comment]
@hehongyu1995 are you interested in picking this up again, or should I delete the branch?

**Comment by hehongyu1995** [comment]
@nicklockwood Sorry, i'm busy these days...I will start to doing it in few days. so please keep the branch for now 😀

**Pull request closed without merging**
